/**
 * Hand-written aliases, by catalog key, for the words people actually type. Most aliases are
 * derived from the catalog names themselves (the parenthetical and slash-separated parts); this
 * list covers the rest. The workbook has no aliases column (OPEN_QUESTIONS: ALIASES).
 */
export const handAliases: Record<string, string[]> = {
  'alcohol-in-the-evening': ['wine', 'beer', 'drinks', 'cocktails', 'nightcap', 'alcohol'],
  'thc-cannabis-for-sleep': ['weed', 'edibles', 'marijuana', 'cannabis'],
  'coffee-after-2pm': ['afternoon coffee', 'late coffee', 'espresso', 'coffee'],
  'second-or-third-coffee': ['second coffee', 'third coffee', 'too much coffee'],
  'omega-3-fish-oil': ['fish oil', 'omega 3', 'omega-3'],
  'sunscreen-daily-spf-30': ['spf', 'sun cream', 'sunblock'],
  'yoga-pilates-studio': ['pilates', 'reformer', 'reformer pilates', 'yoga studio', 'yoga'],
  'premium-gym-membership-equinox-life-time': ['equinox', 'lifetime', 'life time'],
  'facials-monthly': ['facial', 'facials'],
  'retinol-retinoid-nightly': ['tretinoin', 'retin-a', 'retinoid', 'retinol'],
  'screens-phone-in-bed': ['phone in bed', 'scrolling in bed', 'phone before bed'],
  'late-dinner-within-2-3-h-of-bed': ['late dinner', 'eating late', 'dinner'],
  'training-after-7pm': ['evening workout', 'late workout', 'evening training', 'night workout'],
  'vitamin-d3': ['vitamin d', 'd3'],
  'magnesium-any-form': ['magnesium glycinate', 'magnesium citrate', 'mag glycinate', 'magnesium'],
  'greens-powder-ag1-etc': ['athletic greens', 'greens', 'ag1'],
  'meditation-app-calm-headspace': ['meditation app', 'calm', 'headspace'],
  'fitness-app-subscription-peloton-app-apple-fitness-ladder': [
    'fitness app',
    'apple fitness',
    'peloton',
  ],
  'massage-membership-massage-envy-squeeze': ['massage envy', 'squeeze'],
  'recovery-studio-membership-restore-remedy-place-othership': ['restore', 'othership'],
  'boutique-class-membership-barry-s-soulcycle-f45-orangetheory': [
    "barry's",
    'barrys',
    'soulcycle',
    'orangetheory',
    'f45',
  ],
  'cold-plunge-ice-bath': ['cold plunge', 'ice bath', 'plunge'],
  'cold-shower-morning': ['cold shower', 'cold showers'],
  'hot-bath-shower-1-2-h-before-bed': ['hot bath', 'bath before bed'],
  'sauna-post-workout-or-evening': ['sauna'],
  'eight-sleep-cooling-mattress-pad': ['eight sleep', 'cooling pad', 'chilipad'],
  'continuous-glucose-monitor-no-diabetes': ['cgm', 'glucose monitor', 'levels'],
  'blood-panel-subscription-function-etc': ['function health', 'blood panel', 'bloodwork'],
  'red-light-therapy-panel': ['red light', 'red light panel'],
  'weighted-blanket': ['weighted blanket'],
  'mouth-tape': ['mouth tape'],
  'collagen-drinks-and-beauty-gummies': ['collagen gummies', 'beauty gummies', 'collagen drink'],
  'collagen-peptides': ['collagen powder', 'collagen'],
  'vitamin-c-serum': ['vitamin c serum', 'vit c serum'],
  'toner-hydrating-or-balancing': ['toner'],
  'eye-cream-when-you-already-use-a-moisturiser': ['eye cream'],
  'ashwagandha-ksm-66-sensoril': ['ashwagandha', 'ksm-66', 'ksm 66'],
  'sleep-gummies-blend': ['sleep gummies', 'olly'],
  'protein-powder': ['whey', 'protein shake', 'protein'],
  'creatine-monohydrate': ['creatine'],
  'electrolytes-lmnt-etc': ['lmnt', 'electrolytes', 'liquid iv'],
  'nicotine-pouches-vape': ['zyn', 'vape', 'nicotine', 'pouches'],
  'energy-drinks': ['red bull', 'monster', 'celsius', 'energy drink'],
  'matcha-green-tea-in-the-afternoon': ['matcha', 'green tea'],
  'afternoon-nap-after-3pm-or-over-30-min': ['nap', 'naps', 'napping'],
  'consistent-wake-time-30-min': ['wake time', 'same wake time'],
  'melatonin': ['melatonin gummies'],
  'l-theanine': ['theanine'],
  'gym-membership': ['gym', 'planet fitness', '24 hour fitness'],
  'personal-trainer': ['trainer', 'pt sessions'],
  'massage-monthly': ['massage'],
  'acupuncture': ['acupuncture'],
  'chiropractor-maintenance-visits': ['chiro', 'chiropractor'],
  'cryotherapy-sessions': ['cryo', 'cryotherapy'],
  'float-tank': ['float', 'float tank', 'sensory deprivation'],
  'meal-delivery-or-meal-prep-service': ['meal prep', 'meal delivery', 'factor', 'hellofresh'],
  'nutrition-or-calorie-app-premium': ['myfitnesspal', 'calorie app', 'macros app'],
  'air-purifier-bedroom': ['air purifier', 'purifier'],
  'white-noise-sound-machine': ['white noise', 'sound machine'],
  'sunrise-alarm-hatch-etc': ['hatch', 'sunrise alarm'],
  'blue-light-blocking-glasses': ['blue light glasses', 'blue blockers'],
  'bedroom-temperature-thermostat': ['thermostat', 'bedroom temperature', 'room temperature'],
  'morning-sunlight-10-min-outdoors': ['morning sunlight', 'morning light', 'sunlight'],
  'journaling-worry-list-before-bed': ['journaling', 'journal', 'worry list'],
};
