import { mkdir, writeFile } from 'node:fs/promises';
import { decisionEffects, decisionScenarios, simulateDecisionCell } from '@distill/sim';
import type { DecisionCell } from '@distill/sim';

/**
 * Measures the estimate-based decision policy (docs/ALGORITHM-IDENTITY.md) on synthetic people.
 * Usage: pnpm sim:decide [--trials N] [--only id,id] [--seed N]
 */
const args = process.argv.slice(2);
const flag = (name: string) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
};
const trials = Number(flag('--trials') ?? 1500);
const seed = Number(flag('--seed') ?? 20261008);
const only = flag('--only')?.split(',');
const scenarios = decisionScenarios.filter((s) => !only || only.includes(s.id));

const pct = (value: number | null) => (value === null ? '–' : `${(100 * value).toFixed(1)}%`);
const rateText = (r: { value: number | null; interval95: readonly [number, number] | null } | null) =>
  !r || r.value === null || !r.interval95
    ? '–'
    : `${pct(r.value)} [${(100 * r.interval95[0]).toFixed(1)}, ${(100 * r.interval95[1]).toFixed(1)}]`;

const cells: DecisionCell[] = [];
const started = Date.now();
for (const scenario of scenarios) {
  for (const effect of decisionEffects) {
    const cell = simulateDecisionCell(scenario, effect, trials, seed);
    cells.push(cell);
    const o = cell.outcomes;
    process.stderr.write(
      `${scenario.id.padEnd(24)} effect ${String(effect).padStart(5)}  helps ${pct(o.helps / trials).padStart(6)}  costs ${pct(o.costs_you / trials).padStart(6)}  nothing ${pct(o.no_detectable_benefit / trials).padStart(6)}  too-close ${pct(o.too_close_final / trials).padStart(6)}  days ${cell.meanDays?.toFixed(1) ?? '–'}\n`,
    );
  }
}
const lines: string[] = [];
lines.push(`# Decision policy simulation (estimate_v2)`, '');
lines.push(
  `Generated by \`pnpm sim:decide\` with ${trials} attempts per cell and seed ${seed}. Synthetic people from the Phase 6 generator; the real registration, check-in, analysis and decision code. Rates are per attempt, with Wilson 95% intervals.`,
  '',
);
lines.push('## Null nights (true effect 0): how often the policy is wrong, and how often it correctly says "does nothing"', '');
lines.push('| Scenario | Kept or "costs you" (false positive) | "Does nothing" (correct) | Too close at day 28 | Mean days to a decision |');
lines.push('| --- | --- | --- | --- | --- |');
for (const cell of cells.filter((c) => c.effect === 0))
  lines.push(
    `| ${cell.scenario.label} | ${rateText(cell.falsePositive)} | ${rateText(cell.correctNothing)} | ${pct(cell.outcomes.too_close_final / cell.trials)} | ${cell.meanDays?.toFixed(1) ?? '–'} |`,
  );
lines.push('', '## Real effects: how often the policy finds them, and in which direction', '');
lines.push('| Scenario | Effect | Correct call | Wrong direction | Called "does nothing" (miss) | Too close at day 28 | Decided by day 14 | By day 21 | By day 28 |');
lines.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- |');
for (const cell of cells.filter((c) => c.effect !== 0)) {
  const by = (day: number) => pct((cell.decidedByDay[String(day)] ?? 0) / cell.trials);
  lines.push(
    `| ${cell.scenario.label} | ${cell.effect > 0 ? '+' : ''}${cell.effect} | ${rateText(cell.power)} | ${rateText(cell.wrongDirection)} | ${rateText(cell.missedAsNothing)} | ${pct(cell.outcomes.too_close_final / cell.trials)} | ${by(14)} | ${by(21)} | ${by(28)} |`,
  );
}
lines.push('', `Run time ${((Date.now() - started) / 1000).toFixed(0)} s.`, '');
await mkdir('data', { recursive: true });
await writeFile('data/decision-results.json', JSON.stringify({ trials, seed, cells }, null, 2));
await writeFile('docs/DECISION-POWER.md', lines.join('\n'));
process.stdout.write(lines.join('\n'));
