import { fork } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import {
  simulateCell,
  powerScenarios,
  sensitivityScenarios,
  metricScenarios,
  coverageScenarios,
  effectGrid,
  metricModels,
  assertSeed,
} from '@distill/sim';
import type { CellResult, Scenario } from '@distill/sim';

type Job = { scenario: Scenario; effect: number; trials: number };
export async function sourceHash() {
  const paths: string[] = ['data/catalog.json'];
  async function walk(path: string) {
    for (const entry of await readdir(path, { withFileTypes: true })) {
      const child = `${path}/${entry.name}`;
      if (entry.isDirectory()) await walk(child);
      else if (
        entry.name.endsWith('.ts') &&
        !entry.name.endsWith('.test.ts') &&
        !['index.ts', 'demo.ts', 'local.ts', 'guidance.ts'].includes(entry.name)
      )
        paths.push(child);
    }
  }
  await walk('packages/sim/src');
  await walk('packages/engine/src');
  paths.push('scripts/sim-power.ts');
  const hash = createHash('sha256');
  for (const path of paths.sort()) hash.update(path).update(await readFile(path));
  return hash.digest('hex');
}
const args = process.argv.slice(2);
function option(name: string, fallback: number) {
  const values = args.filter((arg) => arg.startsWith(`--${name}=`));
  if (values.length > 1) throw new Error(`Duplicate ${name}`);
  const value = values[0] ? Number(values[0].split('=')[1]) : fallback;
  if (
    !Number.isInteger(value) ||
    value < 0 ||
    value > (name === 'seed' ? 0xffffffff : 100000) ||
    (name !== 'seed' && value === 0)
  )
    throw new Error(`Invalid ${name}`);
  return value;
}
function percent(rate: CellResult['decisive']) {
  if (rate.value === null || !rate.interval95) return '—';
  return `${(rate.value * 100).toFixed(1)}% [${(rate.interval95[0] * 100).toFixed(1)}, ${(rate.interval95[1] * 100).toFixed(1)}]`;
}
function render(cells: CellResult[], metadata: Record<string, unknown>) {
  const lines = [
    '# Simulation and power',
    '',
    'Generated by `pnpm sim:power`. These are synthetic model results, not estimates from real wearable users. Full counts, scenarios, seeds and Wilson 95% intervals are in [power-results.json](../data/power-results.json).',
    '',
    '![Probability of a decisive verdict by injected effect](assets/power.png)',
    '',
    '## Method and assumptions',
    '',
    'Each attempt generates a new seeded person, runs the actual baseline, registration, daily check-in and statistics code, and counts any failed baseline or insufficient data as Inconclusive. No attempts are discarded. New experiments test help and hurt with a shared 5% budget; legacy saved rules stay unchanged. Exact tests enumerate the original constrained block assignment space. Intervals are disabled for power-only cells; this does not change the test or verdict.',
    '',
    'The reference outcome is total sleep. Effects are in each person’s stationary standard deviation, before clipping; HRV uses log space with a lognormal sensor model. The reported personal swing is a finite-sample MAD estimate and can differ from the injected unit. Baselines span the specified number of calendar nights, with illness and missing measurements excluded. Reference assumptions: AR(1) rho 0.35, weekend shift 0.25 swings, 2% illness, 10% missing taps, 2% missing measurements and independent sensor noise equal to 10% of the marginal standard deviation. Missing taps, illness and missing metrics are independent of outcome and assignment unless a stress scenario says otherwise. This is an assumption, not established behavior in real users.',
    '',
    'Means, bounds, person heterogeneity, autocorrelation and noise are declared engineering assumptions. Catalog swing text is preserved in model provenance; numeric conversions are transparent in `packages/sim/src/model.ts`. Other outcomes are model sensitivity checks, not clinical recommendations about raising/lowering those measurements. HRV effects are injected in log units; interval coverage is assessed in the raw units that the card displays.',
    '',
    'AR(1) innovations preserve stationary marginal variance ([Forecasting: Principles and Practice](https://otexts.com/fpp3/AR.html)). Monte Carlo proportions include [Wilson binomial intervals](https://www.itl.nist.gov/div898/handbook/prc/section2/prc241.htm). The exact randomization null is a sharp no-effect null, not a claim of validity under arbitrary treatment-dependent missingness ([Berkeley randomization notes](https://www.stat.berkeley.edu/~stark/Teach/S240/Notes/ch3.htm)).',
    '',
    '## Schedule comparison',
    '',
    'Every percentage below includes its Monte Carlo 95% interval. Power is decisive/all attempts. At zero effect a decisive result is a false positive. Wrong-direction rate is wrong verdict/all attempts, not wrong/decisive.',
    '',
    '| Schedule | Null false positive | Power at 0.8 | Power at 1.2 | Wrong direction at 0.8 |',
    '| --- | --- | --- | --- | --- |',
  ];
  const find = (id: string, effect: number) =>
    cells.find((cell) => cell.scenario.id === id && cell.effect === effect)!;
  for (const scenario of powerScenarios) {
    const zero = find(scenario.id, 0),
      small = find(scenario.id, 0.8),
      large = find(scenario.id, 1.2);
    lines.push(
      `| ${scenario.label} | ${percent(zero.decisive)} (${zero.nullControl}) | ${percent(small.decisive)} | ${percent(large.decisive)} | ${percent(small.wrongDirection!)} |`,
    );
  }
  lines.push(
    '',
    'Null control “supported” means the entire Monte Carlo interval is at or below 5%; “uncertain” overlaps 5%; “failed” is entirely above 5%. This classification distinguishes sampling uncertainty from evidence of excess errors.',
    '',
    '## Sensitivity and harm checks',
    '',
    '| Scenario | Null false positive | Power +0.8 | Power +1.2 | Power −1.2 | Wrong direction −1.2 |',
    '| --- | --- | --- | --- | --- | --- |',
  );
  for (const scenario of [...sensitivityScenarios, ...metricScenarios]) {
    const zero = find(scenario.id, 0),
      small = find(scenario.id, 0.8),
      large = find(scenario.id, 1.2),
      hurt = find(scenario.id, -1.2);
    lines.push(
      `| ${scenario.label} | ${percent(zero.decisive)} (${zero.nullControl}) | ${percent(small.decisive)} | ${percent(large.decisive)} | ${percent(hurt.decisive)} | ${percent(hurt.wrongDirection!)} |`,
    );
  }
  lines.push(
    '',
    '## Interval coverage',
    '',
    'The current percentile bootstrap resamples scheduled whole blocks within condition, using 1,000 replicates per attempted interval. Coverage means that the 90% displayed interval includes the average paired, clipped raw treatment effect on analyzed dates (including hypothetical on values for off dates). The table conditions on an available interval; availability is reported separately so failed intervals cannot disappear. A 90% label does not establish 90% coverage under autocorrelation.',
    '',
    '| Scenario | Effect | Interval available | Conditional coverage |',
    '| --- | --- | --- | --- |',
  );
  for (const cell of cells.filter((cell) => cell.scenario.withInterval))
    lines.push(
      `| ${cell.scenario.label} | ${cell.effect} | ${percent(cell.intervalAvailable)} | ${percent(cell.intervalCoverage)} |`,
    );
  const reference = find('42d-3d-reference', 0.8),
    large = find('42d-3d-reference', 1.2);
  lines.push(
    '',
    '## Gate, labels and protocol decision',
    '',
    `The original 14-day layouts produce no decisive verdict, even at 2.0 swings. The spreadsheet’s “0.8 roughly one in three; 1.2 better than even” claim is **not valid for those layouts**. For the explicitly configured 42-day reference, measured power is ${percent(reference.decisive)} at 0.8 and ${percent(large.decisive)} at 1.2.`,
    '',
    'Keep the 0.8 routing threshold as a candidate-priority threshold, not a promise of a two-week answer. Revise the interpretation of the sheet’s good/fair/low labels: they are source expectations, not validated personal probabilities. New `powerGuidance` reports an empirical good/fair/low label only for this named reference protocol (good ≥50%, fair ≥33⅓%, low below that), uses a conservative lower-bound label, and returns unavailable for unsupported protocols or effects. The source workbook and literature effect estimates have not been rewritten.',
    '',
    'The 42-day layout is available as an explicit simulation-backed option; the saved 14-day default is not silently replaced. Changing the duration offered to people requires a product decision about six weeks of participation. Existing registrations, seeds, policies and baseline snapshots remain locked. Simulations support checking false positives under the tested assumptions, not declaring universal validation. Interval undercoverage and treatment-dependent missingness remain limitations; the result card suppresses intervals without demonstrated coverage.',
    '',
    '## Reproducibility',
    '',
    '```json',
    JSON.stringify(metadata, null, 2),
    '```',
    '',
    'Run `pnpm sim:power` to regenerate the full checked-in report and JSON. Run `pnpm sim:plot` after installing `scripts/requirements-sim.txt`. `pnpm sim:power --quick` writes only `.local/power-quick.json` and does not replace the report. `pnpm sim:power --check` checks source provenance. Local checks do not waive real-provider acceptance or spreadsheet source review.',
    '',
  );
  return lines.join('\n');
}
async function main() {
  if (args[0] === '--worker') {
    const { jobs, seed } = JSON.parse(args[1]!) as { jobs: Job[]; seed: number };
    const cells: CellResult[] = [];
    for (const job of jobs) {
      const result = simulateCell(job.scenario, job.effect, job.trials, seed);
      cells.push(result);
      process.send?.({
        progress: `${job.scenario.id}: effect ${job.effect}, ${job.trials} trials`,
      });
    }
    process.send?.({ cells });
    process.disconnect?.();
    return;
  }
  if (
    args.some(
      (arg) =>
        !/^--(quick|check)$|^--(trials|null-trials|coverage-trials|workers|seed)=\d+$/.test(arg),
    )
  )
    throw new Error('Unknown argument');
  if (args.includes('--check')) {
    const report = JSON.parse(await readFile('data/power-results.json', 'utf8')) as {
      metadata: { sourceHash: string };
    };
    if (report.metadata.sourceHash !== (await sourceHash()))
      throw new Error('Power report is stale; regenerate after changing the model or engine');
    console.log('Power report source provenance is current');
    return;
  }
  const quick = args.includes('--quick'),
    trials = option('trials', quick ? 20 : 500),
    nullTrials = option('null-trials', quick ? 40 : 2000),
    coverageTrials = option('coverage-trials', quick ? 10 : 250);
  const seed = option('seed', 20261003);
  assertSeed(seed);
  const workers = option('workers', 4);
  if (workers > 8) throw new Error('Use at most eight workers');
  const startingHash = await sourceHash();
  const jobs: Job[] = [];
  for (const scenario of powerScenarios)
    for (const effect of effectGrid)
      jobs.push({ scenario, effect, trials: effect === 0 ? nullTrials : trials });
  for (const scenario of [...sensitivityScenarios, ...metricScenarios])
    for (const effect of [0, 0.8, 1.2, -1.2])
      jobs.push({ scenario, effect, trials: effect === 0 ? nullTrials : trials });
  for (const scenario of coverageScenarios)
    for (const effect of [0, 0.8, 1.2]) jobs.push({ scenario, effect, trials: coverageTrials });
  const partitions: Job[][] = Array.from({ length: workers }, () => []);
  const loads = Array<number>(workers).fill(0);
  const weight = (job: Job) =>
    job.trials * (job.scenario.withInterval ? 5 : 1) * (job.scenario.schedule.totalDays ?? 14);
  for (const job of [...jobs].sort((a, b) => weight(b) - weight(a))) {
    const index = loads.indexOf(Math.min(...loads));
    partitions[index]!.push(job);
    loads[index] = loads[index]! + weight(job);
  }
  const results = await Promise.all(
    partitions.map(
      (partition) =>
        new Promise<CellResult[]>((accept, reject) => {
          const child = fork(
            fileURLToPath(import.meta.url),
            ['--worker', JSON.stringify({ jobs: partition, seed })],
            { stdio: ['ignore', 'inherit', 'inherit', 'ipc'] },
          );
          let received = false;
          child.on('message', (message: { progress?: string; cells?: CellResult[] }) => {
            if (message.progress) console.log(message.progress);
            if (message.cells) {
              received = true;
              accept(message.cells);
            }
          });
          child.on('error', reject);
          child.on('exit', (code) => {
            if (code !== 0 || !received) reject(new Error(`Simulation worker exited ${code}`));
          });
        }),
    ),
  );
  const cells = results
    .flat()
    .sort((a, b) => a.scenario.id.localeCompare(b.scenario.id) || a.effect - b.effect);
  if (startingHash !== (await sourceHash()))
    throw new Error('Simulation sources changed during the run; regenerate from a stable tree');
  const metadata = {
    version: 1,
    seed,
    trials,
    nullTrials,
    coverageTrials,
    bootstrapIterations: 1000,
    attemptedTrials: cells.reduce((sum, cell) => sum + cell.trials, 0),
    sourceHash: await sourceHash(),
    generator: 'stationary AR(1), independent streams, bounded metrics, lognormal HRV',
    metricModels,
    inference:
      'exact constrained block randomization; dual tails at 0.025 each unless explicitly legacy',
    quick,
  };
  await mkdir(quick ? '.local' : 'data', { recursive: true });
  await writeFile(
    resolve(quick ? '.local/power-quick.json' : 'data/power-results.json'),
    JSON.stringify({ metadata, cells }, null, 2) + '\n',
  );
  if (!quick) await writeFile('docs/POWER.md', render(cells, metadata));
  console.log(
    `Completed ${metadata.attemptedTrials} attempts. ${quick ? 'Quick results only; not validation.' : 'Wrote data/power-results.json and docs/POWER.md.'}`,
  );
}
await main();
